// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBia_TVDjLdXkvaoSo-V1bFG3ym2L7vdDs',
    appId: '1:443296147013:web:48a9a08840f596dc67252c',
    messagingSenderId: '443296147013',
    projectId: 'datejot-65e59',
    authDomain: 'datejot-65e59.firebaseapp.com',
    storageBucket: 'datejot-65e59.appspot.com',
    measurementId: 'G-WKTGKX5DGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0Cg1buKByO6fUbycZuj80hc5XWoWQnto',
    appId: '1:443296147013:android:f57011caae93c3b367252c',
    messagingSenderId: '443296147013',
    projectId: 'datejot-65e59',
    storageBucket: 'datejot-65e59.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjzBbTMFV_9xr_2-mhfKqm9gZKEJsqemI',
    appId: '1:443296147013:ios:4d8a9b7b2f11c24067252c',
    messagingSenderId: '443296147013',
    projectId: 'datejot-65e59',
    storageBucket: 'datejot-65e59.appspot.com',
    iosClientId:
        '443296147013-t8lp2opeea7jvbmcmr5ln2ce3it33tc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateJot',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjzBbTMFV_9xr_2-mhfKqm9gZKEJsqemI',
    appId: '1:443296147013:ios:4d8a9b7b2f11c24067252c',
    messagingSenderId: '443296147013',
    projectId: 'datejot-65e59',
    storageBucket: 'datejot-65e59.appspot.com',
    iosClientId:
        '443296147013-t8lp2opeea7jvbmcmr5ln2ce3it33tc6.apps.googleusercontent.com',
    iosBundleId: 'com.example.dateJot',
  );
}
